name: Documentation Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'optrace/**'
      - 'examples/**'
      
jobs:
  doc_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    
    # these dependencies will be installed by the setup-headless-display action
    # prior install to enable caching
    - name: Headless display cached install
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: runner.os == 'Linux'
      with:
        version: 1.0
        packages: libglx-mesa0 libgl1 xvfb x11-xserver-utils libdbus-1-3 libegl1 libopengl0 \
                  libosmesa6 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
                  libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xinput0 \
                  libxkbcommon-x11-0 mesa-utils x11-utils libgbm1 libgl1-mesa-dri libglx-mesa0 mesa-libgallium
    
    ## needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v4
      with:
        qt: true
      
    # run tests 
    - name: Run tox
      uses: lsst-sqre/run-tox@v1
      with:
        python-version: ${{ matrix.python-version }}
        tox-envs: "docsbuildcheck,doctest"
        tox-plugins: "tox-gh-actions"
        tox-posargs: "-v"
        cache-key-prefix: ".tox"

