name: Documentation Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      
jobs:
  doc_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    
    ## needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3
      with:
        qt: true
      
    # set up python and dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        
    - name: Test doc building
      run: tox -e docsbuildcheck -- -v

    - name: Test code snippets
      run: tox -r -e doctest -- -v

    - name: Test links
      run: tox -e linkcheck -- -v 
