name: Documentation Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'optrace/**'
      - 'examples/**'
      
jobs:
  doc_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    
    ## needed for the x-server to work
    - name: Setup headless display
      uses: drocheam/setup-headless-display-action@main
      with:
        qt: true
      
    # run tests 
    - name: Run tox
      uses: lsst-sqre/run-tox@v1
      with:
        python-version: ${{ matrix.python-version }}
        tox-envs: "docsbuildcheck,doctest"
        tox-plugins: "tox-gh-actions"
        tox-posargs: "-v"
        cache-key-prefix: ".tox"

