name: Documentation Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      
jobs:
  doc_test:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 6
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    
    # see https://stackoverflow.com/questions/72874772/pytest-core-dump-on-unbutu-22-04-lts-when-using-pyqt5-with-mayavi-and-pyvirtuald
    - name: Install Qt5
      run: |
        sudo apt-get update
        sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
        
    ## needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
      
    # set up python and dependencies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        
    - name: Test doc building
      run: tox -e docsbuildcheck -- -v

    - name: Test code snippets
      run: tox -e doctest -- -v

    - name: Test links
      run: tox -e linkcheck -- -v 
