name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main    

jobs:
  make_doc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4

    # needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v3
      with:
        qt: true

    # set up python and dependecies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions

    # build the documentation
    - name: Build Sphinx Documentation
      run: |
        tox -e docs -- -v
      
    # publish it
    - name: Publish Sphinx Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
