name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main    

jobs:
  make_doc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4

    # needed for the x-server to work
    - name: Setup headless display
      uses: drocheam/setup-headless-display-action@main
      with:
        qt: true

    # generate documentation 
    - name: Run tox
      uses: lsst-sqre/run-tox@v1
      with:
        python-version: ${{ matrix.python-version }}
        tox-envs: "docs"
        tox-plugins: "tox-gh-actions"
        tox-posargs: "-v"
        cache-key-prefix: ".tox"
      
    # publish it
    - name: Publish Sphinx Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        keep_files: false
        force_orphan: true
