name: Weekly package installation test

# do tests on dispatch and every Wednesday at 13:00 UTC
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 3"

jobs:
  install_test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    
    # these dependencies will be installed by the setup-headless-display action
    # prior install to enable caching
    - name: Headless display cached install
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: runner.os == 'Linux'
      with:
        version: 1.0
        packages: libglx-mesa0 libgl1 xvfb x11-xserver-utils libdbus-1-3 libegl1 libopengl0 \
                  libosmesa6 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
                  libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libxcb-xinerama0 libxcb-xinput0 \
                  libxkbcommon-x11-0 mesa-utils x11-utils
    
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v4
      with:
        qt: true
    
    # needed for pyautogui
    # see https://micwan88.github.io/linux/xauth/2019/10/16/create-xauthority-manually.html
    - name: Create Xauthority manually
      run: |
        touch ~/.Xauthority
        xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
      
    # run tests 
    - name: Run tox
      uses: lsst-sqre/run-tox@v1
      with:
        python-version: ${{ matrix.python-version }}
        tox-envs: "install,docsbuildcheck"
        tox-plugins: "tox-gh-actions"
        tox-posargs: "-v"
        use-cache: false

