name: Python 3.11 Compatibility

# do testing on commits, but only if python files changed
# and files are not in examples/ or tests/
on:
  workflow_dispatch:
  push:
    paths:
      - 'optrace/**'
    tags-ignore:
      - '**'
      
jobs:
  comp_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v3
            
    # needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
      
    # set up python and dependecies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        
    # actual tests
    - name: Python 3.11 tests with tox
      run: |        
        tox -e os -- -v 
