name: Release Package and Examples

on:
  workflow_dispatch:

jobs:
  release:
    timeout-minutes: 3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Zip example folder
        run: zip -r examples.zip examples/      
    
      # don't use tags for versions as all tags need to always be pushed to github to be available
      - name: Extract version
        id: get_version
        run: |
          VERSION1=$(python -c "import importlib.metadata; print(importlib.metadata.version('optrace'))")
          VERSION2=$(git describe --tags --always)
          echo "VERSION=$VERSION1-$VERSION2" >> $GITHUB_ENV

      - name: Get last commit message
        id: last_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}
          name: "optrace ${{ env.VERSION }}"
          body: "**Commit Message**: ${{ env.COMMIT_MSG }}\n**Changelog**: https://drocheam.github.io/optrace/development/changelog.html"
          draft: false
          preserve_order: true
          prerelease: false
          files: |
            dist/*.tar.gz
            examples.zip

