name: Release Package and Examples

on:
  workflow_dispatch:
  push:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed so git describe knows the full context

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Zip example folder
        run: zip -r examples.zip examples/      
      
      - name: Extract version from built package
        id: get_version
        run: |
          VERSION1=$(python -c "import importlib.metadata; print(importlib.metadata.version('your-package-name'))")
          echo "VERSION1=$VERSION1" >> $GITHUB_ENV

      - name: Get latest tag
        id: get_version
        run: |
          echo "VERSION2=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION1 }}-${{ env.VERSION2 }}
          name: "Release ${{ env.VERSION1 }}-${{ env.VERSION2 }}"
          #body: "## Changes in this release\n\n- Add your release notes here"
          draft: false
          preserve_order: true
          prerelease: false
          files: |
            dist/*.tar.gz
            examples.zip

