name: Tests

# do testing on commits, but only if python files changed
# and files are not in examples/ or tests/
on:
  workflow_dispatch:
  push:
    paths:
      - 'optrace/**'

      
jobs:
  tox_test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    
    # see https://stackoverflow.com/questions/72874772/pytest-core-dump-on-unbutu-22-04-lts-when-using-pyqt5-with-mayavi-and-pyvirtuald
    - name: Install Qt5
      run: |
        sudo apt-get update
        sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
        
    # needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
      
    # needed for pyautogui
    # see https://micwan88.github.io/linux/xauth/2019/10/16/create-xauthority-manually.html
    - name: Create Xauthority manually
      run: |
        touch ~/.Xauthority
        xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
        
    # set up python and dependecies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        
    # actual tests
    - name: Test with tox
      run: |        
        tox -- -v 
