name: Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    
    # see https://stackoverflow.com/questions/72874772/pytest-core-dump-on-unbutu-22-04-lts-when-using-pyqt5-with-mayavi-and-pyvirtuald
    - name: Install Qt5
      run: |
        sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
        
    # needed for the x-server to work
    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v1
      
    # set up python and dependecies
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
        
    # actual tests
    - name: Test with tox
      run: |        
        tox -- -v 
