name: Website tests

# do tests on dispatch, every Wednesday at 13:00 UTC and when documentation website has been changed
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed] 
  schedule:
    - cron: "0 13 * * 3"

jobs:
  website_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Install Playwright
      run: |
        npm init -y
        npm install playwright
        npx playwright install --with-deps chromium

    # run standard tests
    - name: Run website tests
      run: bash ./tests/test_website.sh
    
    # check for connections other than github.io
    - name: Run connection tests
      run: bash ./tests/test_connections.sh
